# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Windows Application Driver@0
  inputs:
    OperationType: 'Start'

- task: katalonTask@1
  inputs:
    version: '8.5.5'
    executeArgs: '-retry=0 -testSuitePath="Test Suites/putty" -browserType="Windows" -executionProfile="default" -apiKey="4d690cd5-048f-419d-bba7-f560c06e7ded"'


- task: Windows Application Driver@0
  inputs:
    OperationType: 'Stop'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
